"""What ends up inside the release archive.

`scripts/pack_web.py` runs once, in the release workflow, on a tag -- so nothing
else exercises it and a mistake in it is found by whoever downloads the zip.
Two things about it are worth pinning: that the licence travels with the code,
since the archive is how most people who use the extension ever receive it, and
that the archive is reproducible, which is the reason for the fixed timestamp
and the sorted entries.

The tests build their own tree rather than reading `web/`. `web/vendor/` is
generated by `pixi run web-vendor` and gitignored, so in a fresh checkout -- and
in CI, where `check` runs before the vendoring step -- it does not exist.
"""

from __future__ import annotations

import importlib.util
import json
import zipfile
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]


def load():
    """Import the script by path: `scripts/` is not a package and not installed."""
    spec = importlib.util.spec_from_file_location("pack_web", ROOT / "scripts" / "pack_web.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def tree(tmp_path):
    """A repository shaped like this one, small enough to assert on whole."""
    web = tmp_path / "web"
    (web / "src").mkdir(parents=True)
    (web / "vendor").mkdir()
    (web / "manifest.json").write_text(json.dumps({"version": "9.9.9"}), encoding="utf-8")
    (web / "README.md").write_text("readme", encoding="utf-8")
    (web / "src" / "report.js").write_text("// code", encoding="utf-8")
    (web / "vendor" / "plotly.min.js").write_text("// plotly", encoding="utf-8")
    # Developer scaffolding, which must stay out of the archive.
    (web / "tests").mkdir()
    (web / "tests" / "parity.test.mjs").write_text("// tests", encoding="utf-8")
    (web / "package.json").write_text("{}", encoding="utf-8")
    (tmp_path / "LICENSE").write_text("BSD 3-Clause License\n", encoding="utf-8")
    return tmp_path


def packed(module, tree):
    """Run `main` against `tree` and hand back the archive it wrote."""
    module.ROOT = tree
    module.WEB = tree / "web"
    module.DIST = tree / "dist"
    module.main()
    return zipfile.ZipFile(tree / "dist" / "isambard-utilisation-9.9.9.zip")


def test_the_licence_ships_inside_the_archive(tree):
    """The zip is a redistribution, and most of its readers never see the repo."""
    module = load()
    with packed(module, tree) as archive:
        assert archive.read("LICENSE").decode() == "BSD 3-Clause License\n"


def test_the_licence_lands_at_the_root_beside_the_manifest(tree):
    """It comes from outside `web/`, so it is the one entry whose path is invented."""
    module = load()
    with packed(module, tree) as archive:
        top = sorted(name for name in archive.namelist() if "/" not in name)
    assert top == ["LICENSE", "README.md", "manifest.json"]


def test_developer_scaffolding_stays_out(tree):
    module = load()
    with packed(module, tree) as archive:
        names = archive.namelist()
    assert not any(name.startswith("tests/") for name in names)
    assert "package.json" not in names


def test_a_missing_licence_stops_the_release_rather_than_shipping_without_it(tree):
    module = load()
    (tree / "LICENSE").unlink()
    with pytest.raises(SystemExit, match="LICENSE is missing"):
        packed(module, tree)


def test_the_archive_is_reproducible(tree):
    """Sorted entries and a fixed timestamp, so two builds compare byte for byte.

    The licence is what made this worth re-checking: entries are now sorted on
    the name inside the archive rather than on the source path, because those
    two stopped agreeing the moment one file came from outside `web/`.
    """
    module = load()
    with packed(module, tree) as archive:
        first = archive.namelist()
    built = (tree / "dist" / "isambard-utilisation-9.9.9.zip").read_bytes()

    with packed(module, tree) as archive:
        assert archive.namelist() == sorted(first)
    assert (tree / "dist" / "isambard-utilisation-9.9.9.zip").read_bytes() == built
